default_stages: [commit]
repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run ruff check .
        language: system
        pass_filenames: false
      - id: black
        name: black
        entry: uv run black --check .
        language: system
        pass_filenames: false
      - id: ty
        name: ty
        entry: uv run ty check -- .
        language: system
        pass_filenames: false
      - id: isort
        name: isort
        entry: uv run isort --check .
        language: system
        pass_filenames: false
      # - id: pytest
      #   name: pytest
      #   entry: uv run pytest -s
      #   language: system
        # pass_filenames: false
      # - id: interrogate
      #   name: interrogate
      #   entry: uv run interrogate .
      #   language: system
      #   pass_filenames: false